listen: "127.0.0.1:8080"
upstream: "https://апишкавашакрутая.amoboba.ru"
auth_header: "x-api-key"
keys:
  - "sk-ant-ключ_может_быть_не_только_sk-ant_для_этого_поменяй_ссылку_ещё" //<-- этото просто примеры!!!
  - "sk-ant-ключ_может_быть_не_только_sk-ant_для_этого_поменяй_ссылку_ещё" //<-|
exhaustion_markers:
  - "Usage limit reached"
